CREATE SEQUENCE IF NOT EXISTS public.sku_code_seq
  START WITH 1
  INCREMENT BY 1
  MINVALUE 1
  MAXVALUE 9999
  CACHE 10;
CREATE SEQUENCE IF NOT EXISTS public.sku_code_seq
  START WITH 1
  INCREMENT BY 1
  MINVALUE 1
  MAXVALUE 9999
  CACHE 10;

