-- Add requires_pre_pricing flag to customers table
-- This flag indicates whether RRP labels should be generated by default for this customer

ALTER TABLE public.customers
  ADD COLUMN IF NOT EXISTS requires_pre_pricing boolean NOT NULL DEFAULT false;

COMMENT ON COLUMN public.customers.requires_pre_pricing IS 'Whether this customer requires pre-pricing (RRP) labels on their orders by default';

-- Create an index for efficient filtering
CREATE INDEX IF NOT EXISTS idx_customers_requires_pre_pricing
  ON public.customers(org_id, requires_pre_pricing)
  WHERE requires_pre_pricing = true;
