import { type DocumentType } from "@/lib/documents/types";
import { defaultLayoutFor, DOCUMENT_FIELDS } from "@/lib/documents/presets";
export { DOCUMENT_FIELDS, defaultLayoutFor } from "@/lib/documents/presets";
export type DocumentDataContext = {
  orderId?: string;
  batchId?: string;
  customerId?: string;
  payload?: Record<string, unknown>;
};

const sampleLineItems = [
  { description: "Lavender Grosso", quantity: 120, unitPrice: 3.5, total: 420, sku: "LAV-GRO-01" },
  { description: "Rosemary Upright", quantity: 80, unitPrice: 2.9, total: 232, sku: "ROS-UP-08" },
];

const sampleCustomer = {
  name: "Greenleaf Garden Centre",
  contact: "Mia Reynolds",
  email: "mia@greenleaf.example",
  phone: "+353 86 123 4567",
  address: "12 Meadow Lane, Dublin",
};

const sampleOrg = {
  name: "HortiTrack Demo Nursery",
  email: "orders@hortitrack.example",
  phone: "+353 1 234 5678",
  website: "hortitrack.example",
  address: "45 Glasshouse Road, Wicklow",
};

export async function getDocumentData(
  documentType: DocumentType,
  context?: DocumentDataContext
): Promise<Record<string, unknown>> {
  // Placeholder hooks for future real data fetches; current implementation uses sample data.
  const payload = context?.payload ?? {};
  switch (documentType) {
    case "invoice":
      return {
        title: "Invoice",
        subtitle: "Generated by HortiTrack",
        invoice: { number: "INV-1045", date: "2025-12-08", dueDate: "2025-12-22" },
        customer: sampleCustomer,
        org: sampleOrg,
        lines: sampleLineItems,
        totals: {
          subtotal: 652,
          tax: 135,
          grandTotal: 787,
        },
        ...payload,
      };
    case "delivery_docket":
      return {
        title: "Delivery Docket",
        subtitle: "Thank you for your order",
        docket: { number: "DCK-482", date: "2025-12-09" },
        delivery: { address: "42 Orchard Way, Wicklow", contact: "Padraig O'Connor" },
        lines: sampleLineItems.map((l) => ({ ...l, location: "Bench 3" })),
        notes: "Leave at dock if unattended.",
        ...payload,
      };
    case "order_confirmation":
      return {
        title: "Order Confirmation",
        subtitle: "We received your order",
        order: { number: "SO-2025-310", date: "2025-12-08", requestedDate: "2025-12-15" },
        customer: sampleCustomer,
        lines: sampleLineItems,
        totals: { grandTotal: 787 },
        ...payload,
      };
    case "av_list":
      return {
        title: "Availability List",
        subtitle: "Fresh availability from HortiTrack",
        generatedAt: "2025-12-08",
        items: sampleLineItems.map((l) => ({
          name: l.description,
          size: "2L",
          grade: "A",
          qty: l.quantity,
          price: l.unitPrice,
        })),
        ...payload,
      };
    case "lookin_good":
    default:
      return {
        title: "Lookin' Good List",
        subtitle: "Showcase items ready to shine",
        generatedAt: "2025-12-08",
        items: sampleLineItems.map((l, idx) => ({
          name: l.description,
          description: "Healthy, full foliage and strong colour.",
          photo: `https://picsum.photos/seed/lookin-good-${idx}/400/240`,
        })),
        ...payload,
      };
  }
}

